name: Check Julia formatting

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'

      - name: Install JuliaFormatter
        run: julia -e 'using Pkg; Pkg.add("JuliaFormatter")'

      - name: Run formatter check
        run: julia -e 'using JuliaFormatter; isformatted(".", verbose=true) || exit(1)'
