name: CI

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Julia
        uses: https://github.com/julia-actions/setup-julia@v1
        with:
          version: '1.11'

      - name: Install dependencies
        run: julia --project=. -e 'using Pkg; Pkg.instantiate()'

      - name: Run tests
        run: julia --project=. -e 'using Pkg; Pkg.test()'

      - name: Check formatting
        run: julia --project=. -e 'using JuliaFormatter; format(".", verbose=true)'
